### ISSUE TITLE
action container で Makefileつかってみる

### ISSUE THREAD

**Issue by mizmarine** [mizmarine/github-actions-sandbox#19]
#17 つづき
要するにこういう使い勝手だと良いのではないか

```
      - name: Hello world action step dayo
        uses: ./.github/actions/test # Uses an action in the root directory
        id: hello
        with:
          targets:
            - lint
            - test
```
